export type DecisionStatus = "BUY_SETUP" | "SELL_SETUP" | "WAIT" | "NO_TRADE" | "EVENT_LOCKOUT" | "DATA_UNAVAILABLE";
export type Horizon = "SCALP" | "INTRADAY" | "SWING" | "WEEKLY";

export interface Target { label: string; price: number; rationale: string; net_reward_to_risk: number | null }
export interface EvidenceItem { family: string; key: string; direction: number; strength: number; description: string; source: string; ts: string | null; correlated_group: string | null; available: boolean }
export interface Setup {
  instrument: string; bid: number; ask: number; spread: number; data_provider: string; price_timestamp: string; user_timezone: string; horizon: string;
  strategy_id: string; strategy_name: string; strategy_version: string; direction: "BUY" | "SELL"; entry_trigger: string; entry_zone_low: number; entry_zone_high: number; entry_reference: number;
  entry_confirmation_required: boolean; entry_confirmed: boolean; stop_loss: number; stop_rationale: string; targets: Target[]; estimated_spread: number; estimated_slippage: number; estimated_fees_usd: number; estimated_financing_usd: number;
  expiry: string; max_holding_until: string | null; market_regime: Record<string, unknown>; news_risk: Record<string, unknown>; supporting_evidence: EvidenceItem[]; contradictory_evidence: EvidenceItem[]; invalidation_conditions: string[];
  position_size: Record<string, unknown>; total_account_risk_usd: number; total_account_risk_pct: number; aggregate_exposure_after_usd: number; aggregate_exposure_after_pct: number; confidence_low: number; confidence_high: number; confidence_method: string;
  historical_sample_size: number; backtest_approval_status: string; data_quality_status: string; notification_timestamp: string | null; uncertainty_statement: string; evidence_inspector_ref: string; decision_reason: string; conflicting_horizons: string[]; contract_spec_id: string; demo_data: boolean;
}
export interface Decision { decision_id: string; horizon: Horizon; status: DecisionStatus; strategy_id: string | null; strategy_version: string | null; as_of: string; reason: string; score: number | null; regime: string | null; demo_data: boolean; setup: Setup | null; expiry: string | null; evidence_inspector?: Record<string, unknown>; outcome?: Record<string, unknown> | null }
export interface Quote { instrument: string; bid: number; ask: number; mid: number; spread: number; ts: string; provider: string; demo_data: boolean; integrity: { status: string; issues: { code: string; severity: string; message: string }[] }; market_state: string; session: string; user_timezone: string }
export interface Candle { time: number; open: number; high: number; low: number; close: number; volume: number | null; complete: boolean }
export interface UserSettings { timezone: string; account_currency: string; contract_spec: Record<string, unknown>; risk_limits: Record<string, number | string | boolean>; risk_bounds: Record<string, [number, number]>; notification_prefs: Record<string, unknown>; horizons_enabled: Record<string, boolean>; locale: string; theme: string; weekend_risk_ack_at: string | null }
export interface Me { id: string; email: string; role: string; mfa_enabled: boolean; onboarding_completed: boolean }
export interface CalendarEvent { event_id: string; name: string; country: string; currency: string; importance: string; scheduled_ts: string; scheduled_local: string | null; category: string; provider: string; actual: number | null; consensus: number | null; prior: number | null; revised_prior: number | null; verification: string; surprise: number | null; standardised_surprise: number | null; unit: string }
export interface Notification { id: string; kind: string; priority: string; title: string; body: string; payload: Record<string, unknown>; created_at: string; created_local: string; delivery_status: string; delivery_detail: string; read_at: string | null }
export interface Strategy { id: string; name: string; version: string; status: string; horizon: string; hypothesis: string; rationale: string; approved_regimes: string[]; prohibited_regimes: string[]; entry_setup: string; entry_trigger: string; stop_methodology: string; tp1_methodology: string; tp2_methodology: string; min_net_rr: number; spread_limit: number; slippage_limit: number; news_restrictions: string; setup_expiry_minutes: number; max_holding_minutes: number | null; known_failure_regimes: string[]; suspension_rules: Record<string, number>; params: Record<string, number>; production_threshold: number | null; validation_results: Record<string, unknown>; backtest_results: Record<string, unknown>; approval_history: Record<string, unknown>[]; change_log: Record<string, unknown>[]; suspension_reason: string | null; approval_note: string; required_data: string[]; sessions: string[]; timeframes: string[]; confirmation_rules: string[]; invalidation_rules: string[]; sizing_methodology: string; retirement_rules: string[]; owner: string }
export interface Gate { code: string; name: string; passed: boolean; applicable: boolean; reason: string }
